#[derive(Copy, Clone, Eq, PartialEq, Debug, strum::EnumString, strum::IntoStaticStr)]
#[strum(ascii_case_insensitive)]
pub enum Filter {
    // list obtained from 'convert -list filter'
    Bartlett,
    Blackman,
    Bohman,
    Box,
    Catrom,
    Cosine,
    Cubic,
    Gaussian,
    Hamming,
    Hann,
    Hermite,
    Jinc,
    Kaiser,
    Lagrange,
    Lanczos,
    Lanczos2,
    Lanczos2Sharp,
    LanczosRadius,
    LanczosSharp,
    Mitchell,
    Parzen,
    Point,
    Quadratic,
    Robidoux,
    RobidouxSharp,
    Sinc,
    SincFast,
    Spline,
    Triangle,
    Welch,
}
